import type { JobListItem } from '@/entities/job';

export const MOCK_BOOKMARKED_JOBS: JobListItem[] = [
  {
    id: 'bookmark-1',
    companyName: '(주)터빈크루',
    title: '2026 AI 개발 인턴 채용 (Vision AI 연구개발)',
    source: 'school',
    subLabel: 'MOU   ·   교내 모집',
    location: '서울',
    employmentType: '인턴',
    dDay: 17,
    deadlineLabel: '08.14 마감',
    isClosed: false,
    isBookmarked: true,
    detailHref: '/jobs/school/1',
  },
  {
    id: 'bookmark-2',
    companyName: '한국전력공사',
    title: '2026년 고졸 채용형 인턴 모집',
    source: 'school',
    subLabel: 'MOU   ·   교내 모집',
    location: '서울',
    employmentType: '인턴',
    dDay: 17,
    deadlineLabel: '08.14 마감',
    isClosed: false,
    isBookmarked: true,
    detailHref: '/jobs/school/2',
  },
  {
    id: 'bookmark-3',
    companyName: '한전KDN',
    title: '2026 고졸 채용형 인턴 모집',
    source: 'school',
    subLabel: '공기업   ·   교내 모집',
    location: '서울',
    employmentType: '인턴',
    dDay: 17,
    deadlineLabel: '08.14 마감',
    isClosed: false,
    isBookmarked: true,
    detailHref: '/jobs/school/3',
  },
  {
    id: 'bookmark-4',
    companyName: '카카오',
    title: '2026 소프트웨어 개발 인턴 채용',
    source: 'external',
    subLabel: '외부 공고   ·   카카오 채용',
    location: '서울',
    employmentType: '인턴',
    dDay: 17,
    deadlineLabel: '08.14 마감',
    isClosed: false,
    isBookmarked: true,
    detailHref: '/jobs/external/4',
  },
];
