import type { JobListItem } from '@/entities/job';

/**
 * 디자인 확인용 목업 데이터.
 * API 연동 이슈에서 이 배열을 `useQuery` 응답으로 교체한다.
 * `subLabel`의 " · " 앞뒤 공백은 Figma(node 500:1509)의 카드 인스턴스가 실제로 쓰던 3칸 공백이다.
 */
export const MOCK_JOB_LIST_ITEMS: JobListItem[] = [
  {
    id: 'job-1',
    companyName: '한국전력공사',
    title: '2026년 고졸 채용형 인턴 모집',
    source: 'school',
    subLabel: 'MOU   ·   교내 모집',
    location: '서울',
    employmentType: '인턴',
    dDay: 17,
    deadlineLabel: '08.14 마감',
    isClosed: false,
    isBookmarked: true,
    detailHref: '/jobs/school/1',
  },
  {
    id: 'job-2',
    companyName: '우아한형제들',
    title: '웹 프론트엔드 주니어 개발자 채용',
    source: 'external',
    subLabel: '외부 공고   ·   기업 채용 페이지',
    location: '서울',
    employmentType: '인턴',
    dDay: null,
    deadlineLabel: '08.14',
    isClosed: true,
    isBookmarked: false,
    detailHref: '/jobs/external/2?variant=closed',
  },
  {
    id: 'job-3',
    companyName: '카카오',
    title: '2026 소프트웨어 개발 인턴 채용',
    source: 'external',
    subLabel: '외부 공고   ·   카카오 채용',
    location: '서울',
    employmentType: '인턴',
    dDay: 17,
    deadlineLabel: '08.14 마감',
    isClosed: false,
    isBookmarked: false,
    detailHref: '/jobs/external/3',
  },
  {
    id: 'job-4',
    companyName: '우아한형제들',
    title: '웹 프론트엔드 주니어 개발자 채용',
    source: 'external',
    subLabel: '외부 공고   ·   기업 채용 페이지',
    location: '서울',
    employmentType: '인턴',
    dDay: null,
    deadlineLabel: '08.14',
    isClosed: true,
    isBookmarked: false,
    detailHref: '/jobs/external/4?variant=closed',
  },
  {
    id: 'job-5',
    companyName: '우아한형제들',
    title: '웹 프론트엔드 주니어 개발자 채용',
    source: 'external',
    subLabel: '외부 공고   ·   기업 채용 페이지',
    location: '서울',
    employmentType: '인턴',
    dDay: 17,
    deadlineLabel: '08.14 마감',
    isClosed: false,
    isBookmarked: true,
    detailHref: '/jobs/external/5',
  },
  {
    id: 'job-6',
    companyName: '한국전력공사',
    title: '2026년 고졸 채용형 인턴 모집',
    source: 'school',
    subLabel: 'MOU   ·   교내 모집',
    location: '인천',
    employmentType: '인턴',
    dDay: 17,
    deadlineLabel: '08.14 마감',
    isClosed: false,
    isBookmarked: false,
    detailHref: '/jobs/school/6',
  },
  {
    id: 'job-7',
    companyName: '한국전력공사',
    title: '2026년 고졸 채용형 인턴 모집',
    source: 'school',
    subLabel: 'MOU   ·   교내 모집',
    location: '서울',
    employmentType: '인턴',
    dDay: 17,
    deadlineLabel: '08.14 마감',
    isClosed: false,
    isBookmarked: false,
    detailHref: '/jobs/school/7',
  },
  {
    id: 'job-8',
    companyName: '한국전력공사',
    title: '2026년 고졸 채용형 인턴 모집',
    source: 'school',
    subLabel: 'MOU   ·   교내 모집',
    location: '서울',
    employmentType: '인턴',
    dDay: 17,
    deadlineLabel: '08.14 마감',
    isClosed: false,
    isBookmarked: false,
    detailHref: '/jobs/school/8',
  },
  {
    id: 'job-9',
    companyName: '한국전력공사',
    title: '2026년 고졸 채용형 인턴 모집',
    source: 'school',
    subLabel: 'MOU   ·   교내 모집',
    location: '서울',
    employmentType: '인턴',
    dDay: 17,
    deadlineLabel: '08.14 마감',
    isClosed: false,
    isBookmarked: false,
    detailHref: '/jobs/school/9',
  },
];
