import type { AuditLogEntry } from '@/entities/audit-log';

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    actionType: 'UPDATE',
    actor: { email: 'admin@geti.kr', name: '개발자' },
    auditLogId: 'audit-1',
    changes: [
      { after: '공개', before: '비공개', field: '공개 상태' },
      { after: '개발자', before: '김선생', field: '수정자' },
    ],
    detailSummary: '공고 공개 상태 변경',
    occurredAt: '2026.08.01 14:32:18',
    requestPath: '/admin/jobs/JOB-2026-081',
    result: 'SUCCESS',
    resultMessage: '정상 처리',
    summary: '공개 상태 변경',
    targetId: 'JOB-2026-081',
    targetType: '공고',
  },
  {
    actionType: 'CREATE',
    actor: { email: 'admin@geti.kr', name: '개발자' },
    auditLogId: 'audit-2',
    changes: [{ after: '게시', before: '-', field: '프로그램 상태' }],
    detailSummary: '프로그램 등록',
    occurredAt: '2026.08.01 14:32:18',
    requestPath: '/admin/programs/PRG-042',
    result: 'SUCCESS',
    resultMessage: '정상 처리',
    summary: '프로그램 등록',
    targetId: 'PRG-042',
    targetType: '프로그램',
  },
  {
    actionType: 'DELETE',
    actor: { email: 'admin@geti.kr', name: '개발자' },
    auditLogId: 'audit-3',
    changes: [{ after: '삭제', before: '활성', field: '기업 상태' }],
    detailSummary: '기업 Soft Delete',
    occurredAt: '2026.08.01 14:32:18',
    requestPath: '/admin/companies/COM-018',
    result: 'SUCCESS',
    resultMessage: '정상 처리',
    summary: '기업 Soft Delete',
    targetId: 'COM-018',
    targetType: '기업',
  },
  {
    actionType: 'UPDATE',
    actor: { email: 'admin@geti.kr', name: '개발자' },
    auditLogId: 'audit-4',
    changes: [{ after: 'ACTIVE', before: 'PENDING', field: '회원 상태' }],
    detailSummary: '회원 상태 변경',
    occurredAt: '2026.08.01 14:32:18',
    requestPath: '/admin/users/USR-10103',
    result: 'FAILED',
    resultMessage: '권한 확인 실패',
    summary: '회원 상태 변경',
    targetId: 'USR-10103',
    targetType: '회원',
  },
  {
    actionType: 'ANSWER',
    actor: { email: 'admin@geti.kr', name: '개발자' },
    auditLogId: 'audit-5',
    changes: [{ after: '답변 완료', before: '처리 중', field: '문의 상태' }],
    detailSummary: '문의 답변 완료',
    occurredAt: '2026.08.01 14:32:18',
    requestPath: '/admin/inquiries/INQ-077',
    result: 'SUCCESS',
    resultMessage: '정상 처리',
    summary: '문의 답변 완료',
    targetId: 'INQ-077',
    targetType: '문의',
  },
];
